[package]
name = "pink-proxy"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.0.0-beta", default-features = false }
awc = { version = "3.0.0-beta", default-features = false, features = [
    "rustls",
] }

serde = "1"
uuid = { version = "0.8.2", features = ["v4", "serde"] }
#reqwest = { version = "0.11.4" }
#bytes = "1.0.1"
env_logger = "0.9.0"
log = "0.4"
